/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JrButton {
        "variant": 'primary' | 'warning';
    }
    interface JrTable {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJrButtonElement extends Components.JrButton, HTMLStencilElement {
    }
    var HTMLJrButtonElement: {
        prototype: HTMLJrButtonElement;
        new (): HTMLJrButtonElement;
    };
    interface HTMLJrTableElement extends Components.JrTable, HTMLStencilElement {
    }
    var HTMLJrTableElement: {
        prototype: HTMLJrTableElement;
        new (): HTMLJrTableElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "jr-button": HTMLJrButtonElement;
        "jr-table": HTMLJrTableElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JrButton {
        "variant"?: 'primary' | 'warning';
    }
    interface JrTable {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "jr-button": JrButton;
        "jr-table": JrTable;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jr-button": LocalJSX.JrButton & JSXBase.HTMLAttributes<HTMLJrButtonElement>;
            "jr-table": LocalJSX.JrTable & JSXBase.HTMLAttributes<HTMLJrTableElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
